out_dir: results
metric_best: ap
wandb:
  use: True
  project: peptides-func
dataset:
  format: OGB
  name: peptides-functional
  task: graph
  task_type: classification_multilabel
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+LapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_LapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
posenc_RWSE:
  enable: False
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 200
  eval_period: 1
  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: cross_entropy
  graph_pooling: mean
gt:
  layer_type: CustomGatedGCN+Transformer
  layers: 6
  n_heads: 4
  dim_hidden: 76  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.1
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
gnn:
  head: mlp_graph
  layers_pre_mp: 0
  layers_post_mp: 2
  dim_inner: 76  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: gelu
  dropout: 0.1
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 250
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
