out_dir: results
metric_best: f1
wandb:
  use: True
  project: Pascal
dataset:
  format: PyG-VOCSuperpixels
  name: edge_wt_region_boundary
  slic_compactness: 30
  task: graph  # Even if VOC is node-level task, this needs to be set as 'graph'
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: VOCNode+LapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: VOCEdge
  edge_encoder_bn: False
posenc_LapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
posenc_RWSE:
  enable: False
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 50
  eval_period: 1
  ckpt_period: 100
  eval_smoothing_metrics: True
model:
  type: GPSModel
  loss_fun: weighted_cross_entropy
gt:
  layer_type: CustomGatedGCN+Transformer
  layers: 8
  n_heads: 4
  dim_hidden: 68  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.1
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
gnn:
  head: inductive_node
  layers_pre_mp: 0
  layers_post_mp: 2
  dim_inner: 68  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: gelu
  dropout: 0.1
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
